# Change prefix from Ctrl+b to Ctrl+a
unbind C-b
set-option -g prefix C-a

# Kill pane instantly without confirmation prompt
bind x kill-pane

# Enable mouse support (clicking, resizing, scrolling)
set -g mouse on

# Reload config file shortcut
bind r source-file ~/.tmux.conf \; display-message "Config reloaded!"

# Fix terminal colors (ensure truecolor works)
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Tc"

# Set base index for windows and panes to 1 (instead of 0)
set -g base-index 1
setw -g pane-base-index 1

# Faster command delay (avoids Vim esc delay)
set -s escape-time 0

# Vim-style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Clean, minimalist status bar (dark style)
set -g status-style bg=default,fg=black
# set -g status-left ""
set -g status-right ""


# Split panes using n and m (opens in current path)
bind n split-window -h -c "#{pane_current_path}"
bind m split-window -v -c "#{pane_current_path}"

# Unbind the default split keys
unbind '"'
unbind %

# Create new window using a (opens in current path)
bind a new-window -c "#{pane_current_path}"

# Window switching using u and i
bind u previous-window
bind i next-window
